ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS postal_code TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS address TEXT DEFAULT '';

ALTER TABLE deliveries
  ADD COLUMN IF NOT EXISTS postal_code TEXT DEFAULT '';
