ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS booked BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS booked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS booked_by TEXT DEFAULT '';

ALTER TABLE expenses
  ADD COLUMN IF NOT EXISTS booked BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS booked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS booked_by TEXT DEFAULT '';
