ALTER TABLE expenses
  ADD COLUMN IF NOT EXISTS image_data TEXT,
  ADD COLUMN IF NOT EXISTS image_name TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS image_url TEXT DEFAULT '';

ALTER TABLE expenses ALTER COLUMN category DROP NOT NULL;
ALTER TABLE expenses ALTER COLUMN amount DROP NOT NULL;
