ALTER TABLE ai_usage_daily ADD COLUMN IF NOT EXISTS input_tokens BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ai_usage_daily ADD COLUMN IF NOT EXISTS output_tokens BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ai_usage_daily ADD COLUMN IF NOT EXISTS total_tokens BIGINT NOT NULL DEFAULT 0;
